"""initial schema

Hand-written rather than autogenerated: the partial indexes below are load-bearing
(they enforce the run-serialization invariant and back the dispatch hot path), and
autogenerate has a habit of quietly dropping the `postgresql_where` clause.

Every integration test runs `alembic upgrade head` rather than
`metadata.create_all`, so any drift between this file and the ORM models shows up as
a failing test on the next run instead of as a production surprise.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


RUN_STATUS = ("pending", "running", "awaiting_approval", "succeeded", "failed", "cancelled")
STEP_STATUS = (
    "pending",
    "running",
    "retrying",
    "awaiting_approval",
    "succeeded",
    "failed",
    "cancelled",
)
STEP_KIND = ("dummy", "agent_turn", "tool_call", "finalize")


def _enum(name: str, values: tuple[str, ...]) -> pg.ENUM:
    return pg.ENUM(*values, name=name, create_type=False)


def upgrade() -> None:
    for name, values in (
        ("run_status", RUN_STATUS),
        ("step_status", STEP_STATUS),
        ("step_kind", STEP_KIND),
    ):
        op.execute(
            "CREATE TYPE {name} AS ENUM ({vals})".format(
                name=name, vals=", ".join(f"'{v}'" for v in values)
            )
        )

    op.create_table(
        "agent_definitions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "tools", pg.ARRAY(sa.Text()), nullable=False, server_default=sa.text("'{}'::text[]")
        ),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("max_cost_usd", sa.Numeric(12, 6), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "retry_policy", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "on_approval_rejected",
            sa.Text(),
            nullable=False,
            server_default=sa.text("'feed_back_to_model'"),
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.UniqueConstraint("name", "version", name="uq_agent_definitions_name_version"),
        sa.CheckConstraint("max_steps BETWEEN 1 AND 200", name="ck_agent_def_max_steps"),
        sa.CheckConstraint("max_cost_usd > 0", name="ck_agent_def_max_cost"),
        sa.CheckConstraint("timeout_seconds > 0", name="ck_agent_def_timeout"),
    )

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "agent_definition_id",
            sa.Uuid(),
            sa.ForeignKey("agent_definitions.id"),
            nullable=False,
        ),
        sa.Column("status", _enum("run_status", RUN_STATUS), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("input", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("output", pg.JSONB(), nullable=True),
        sa.Column("error", pg.JSONB(), nullable=True),
        sa.Column("client_idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "cancel_requested", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("max_steps", sa.Integer(), nullable=False),
        sa.Column("max_cost_usd", sa.Numeric(12, 6), nullable=False),
        sa.Column("deadline_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("steps_used", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "cache_read_tokens", sa.BigInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "cache_write_tokens", sa.BigInteger(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("cost_usd", sa.Numeric(12, 6), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.CheckConstraint("steps_used >= 0", name="ck_agent_runs_steps_used"),
        sa.CheckConstraint("cost_usd >= 0", name="ck_agent_runs_cost"),
    )
    op.create_index(
        "ix_agent_runs_status_created", "agent_runs", ["status", sa.text("created_at DESC")]
    )
    op.create_index(
        "ix_agent_runs_deadline",
        "agent_runs",
        ["deadline_at"],
        postgresql_where=sa.text("status IN ('pending','running','awaiting_approval')"),
    )
    op.create_index(
        "uq_agent_runs_client_idempotency_key",
        "agent_runs",
        ["client_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("client_idempotency_key IS NOT NULL"),
    )

    op.create_table(
        "steps",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("parent_step_id", sa.Uuid(), sa.ForeignKey("steps.id"), nullable=True),
        sa.Column("kind", _enum("step_kind", STEP_KIND), nullable=False),
        sa.Column("status", _enum("step_status", STEP_STATUS), nullable=False),
        sa.Column("input", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("output", pg.JSONB(), nullable=True),
        sa.Column("error", pg.JSONB(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("max_attempts", sa.Integer(), nullable=False, server_default=sa.text("3")),
        sa.Column("recoveries", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("max_recoveries", sa.Integer(), nullable=False, server_default=sa.text("2")),
        sa.Column(
            "available_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_epoch", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("lease_expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("traceparent", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.UniqueConstraint("run_id", "seq", name="uq_steps_run_seq"),
        sa.CheckConstraint("attempt >= 0", name="ck_steps_attempt"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_steps_max_attempts"),
        sa.CheckConstraint("recoveries >= 0", name="ck_steps_recoveries"),
    )
    # The run-serialization invariant: at most one non-terminal step per run.
    # Enforced here so that a bug in the engine surfaces as an integrity error
    # rather than as two workers advancing the same run in parallel.
    op.create_index(
        "one_active_step_per_run",
        "steps",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('pending','running','retrying','awaiting_approval')"
        ),
    )
    op.create_index(
        "steps_runnable",
        "steps",
        ["available_at"],
        postgresql_where=sa.text("status IN ('pending','retrying')"),
    )
    op.create_index(
        "steps_leased",
        "steps",
        ["lease_expires_at"],
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index("ix_steps_run_seq", "steps", ["run_id", "seq"])

    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "step_id", sa.Uuid(), sa.ForeignKey("steps.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("provider_tool_use_id", sa.Text(), nullable=True),
        sa.Column("arguments", pg.JSONB(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "effect_status", sa.Text(), nullable=False, server_default=sa.text("'in_flight'")
        ),
        sa.Column("effect_policy", sa.Text(), nullable=False),
        sa.Column("result", pg.JSONB(), nullable=True),
        sa.Column("error", pg.JSONB(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("attempt_observed", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "started_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("committed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        # The entire dedupe guarantee. Note the absence of `attempt` from the key
        # this constraint protects: see DESIGN.md section 5.2.
        sa.UniqueConstraint("idempotency_key", name="uq_tool_calls_idempotency_key"),
    )
    op.create_index("ix_tool_calls_run_started", "tool_calls", ["run_id", "started_at"])

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "step_id", sa.Uuid(), sa.ForeignKey("steps.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("request", pg.JSONB(), nullable=False),
        sa.Column("response", pg.JSONB(), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("cost_usd", sa.Numeric(12, 6), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "price_version", sa.Text(), nullable=False, server_default=sa.text("'unknown'")
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", pg.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.create_index("ix_llm_calls_run_created", "llm_calls", ["run_id", "created_at"])

    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "step_id", sa.Uuid(), sa.ForeignKey("steps.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("arguments", pg.JSONB(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column(
            "requested_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("decided_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_index("uq_approval_requests_step", "approval_requests", ["step_id"], unique=True)
    op.create_index(
        "ix_approval_requests_pending",
        "approval_requests",
        ["decision", "requested_at"],
        postgresql_where=sa.text("decision = 'pending'"),
    )

    op.create_table(
        "state_transitions",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "step_id", sa.Uuid(), sa.ForeignKey("steps.id", ondelete="CASCADE"), nullable=True
        ),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=True),
        sa.Column("details", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.create_index(
        "ix_state_transitions_run_created", "state_transitions", ["run_id", "created_at"]
    )

    op.create_table(
        "dummy_effects",
        sa.Column(
            "step_id",
            sa.Uuid(),
            sa.ForeignKey("steps.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "run_id",
            sa.Uuid(),
            sa.ForeignKey("agent_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("executions", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_worker", sa.Text(), nullable=True),
        sa.Column(
            "first_started_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_started_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_dummy_effects_run", "dummy_effects", ["run_id"])


def downgrade() -> None:
    for table in (
        "dummy_effects",
        "state_transitions",
        "approval_requests",
        "llm_calls",
        "tool_calls",
        "steps",
        "agent_runs",
        "agent_definitions",
    ):
        op.drop_table(table)
    for name in ("step_kind", "step_status", "run_status"):
        op.execute(f"DROP TYPE IF EXISTS {name}")
